language: python
python:
  - "3.6"
before_install:
  - sudo apt-get -y install python3-pip
  # install NumPy dependencies
  - sudo apt-get update -qq
  - sudo apt-get install -qq gfortran libatlas-base-dev
  - sudo apt-get install -qq python-numpy
install:
  - python setup.py install
script:
  - nosetests tests
